name: swagger

# This will run when:
# - when new code is pushed to main/develop to make sure the
#   code does compile.
# - when a pull request is created and updated to make sure the
#   code does compile.
on:
  push:
    branches:
      - main
      - develop

  pull_request:

# Check to make sure swagger document is valid
jobs:

  # downloads all the dependencies and compiles the scala code
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: openapi-lint 
        uses: mbowman100/swagger-validator-action@master
        with:
          files: public/swagger.yml
