name: swagger

# This will run when:
# - when new code is pushed to master/develop to make sure the
#   code does compile.
# - when a pull request is created and updated to make sure the
#   code does compile.
on:
  push:
    branches:
      - master
      - develop

  pull_request:

# Check to make sure swagger document is valid
jobs:

  # downloads all the dependencies and compiles the scala code
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: openapi-lint 
        uses: mhiew/redoc-lint-github-action@v2
        with:
          args: 'public/swagger.yml --skip-rule operation-operationId'
